### ISSUE TITLE
Partially builded titanium/structure is not usable

### ISSUE THREAD

**Issue by Arano-kai** [colobot/colobot#1025]
Ver: 0.1.10
OS: Debian (stretch)
If one start `build()` and then interrupt script (by stop or bot destruction), remained titanium/structure become unusable in any manner. Even `radar(Any)` don't catch it.

I suspect that need roll back to cube or act as untransportable, but still usable for `build()` titanium.

**Comment by tomangelo2** [comment]
Like I proposed earlier on Slack, I think that starting build() command (both by astronaut and robots) should create at a beginning a building visible by radar() (optionally it would be visible only with flag, or instead of radar it would be visible for search() ), but with flag `usable=0`. Then alongside with zooming a model like it is currently, shield would be slowly increasing to 100%, and on finish it's flagged `usable=1`. Shield level would be also a progress bar, when building will be interrupted, then another bots will look for a building with `usable=0` and just continue the process from the point where it was interrupted.
It would also allow us to make buildings unusable when damaged in significant level (like after damaging shield to 40%), requiring player to fix it in order to restore its functionality.

**Comment by Nakilon** [comment]
Oh this is why I spent 30 minutes thinking why I can't grab a Titanium. I'm new to this Colobot build and was pressing buttons and cancelled building I guess.
