### ISSUE TITLE
Modifications might interfere with each other

### ISSUE THREAD

**Issue by tomangelo2** [colobot/colobot#1035]
Currently modifications are overriding original files with custom ones. But what if we'll install multiple mods, each with its own custom assets pack, when few of them will replace same file? They override each other according to the order of the alphabet, so 'aaa' modpack will be overriden by 'aab' modpack, which will be overriden by 'ccc' and so on. It doesn't make much problem until these assets fits into each other, but when there will be modpacks with different styles then it will looks strange and require from player manual managing to rename/move/remove directories every time he'll have collision.
I think about 2 solutions:

1. Mod manager, that will allow player to check/uncheck files as needed in dedicated menu (like in OpenTTD, or by separate, optional launcher like in Bethesda games), this one would require another configuration file.
2. Prioritize same mod assets. I mean if we install 2 custom levelpacks 'aaa' and 'aab', each modifing Astronaut files, then game should load 'aaa' version of Astronaut assets when loading levels from 'aaa' modpack and similarly with 'aab' assets for levels from 'aab' modpack. But there's still collision for another levels without their assets.

**Comment by DavivaD** [comment]
First solution makes more sense...

**Comment by krzys-h** [comment]
Just to make the information about the order more complete, because it's slightly more complicated:
1. Files placed directly in the saves directory
2. Mods loaded with -mod commandline parameter, in the order they were specified in
3. Mods loaded from user-specific saves directory, in OS-specific order
4. Mods loaded from system-wide data directory, in OS-specific order
5. Default game data files

OS-specific order is alphabetic on Windows and undefined on Linux (according to Boost docs)
