### ISSUE TITLE
Colobot Gold does not work on Windows XP anymore

### ISSUE THREAD

**Issue by archeYR** [colobot/colobot#1061]
0.1.10 works fine, 0.1.11 complains about missing function in msvcrt.dll, if one of the aims of game is ability to run on old hardware, I think Windows XP should be supported, but if it's not going to happen, please add information to the website about ending support for Windows XP, thanks.
![windows xp professional-2018-01-08-20-55-27](https://user-images.githubusercontent.com/32551254/34689970-aab6adb0-f4b7-11e7-89a5-b6a4ab761f5a.png)

**Comment by krzys-h** [comment]
Hi!
Is that 32 or 64 bit version? We had some problems compiling the official builds due to a compiler bug of some sort so one of them was built by @tomangelo2, not me as usual. Perhaps that introduced this problem.
Dropping WinXP support definitely wasn't intended.

**Comment by archeYR** [comment]
It is 32 bit version.

**Comment by krzys-h** [comment]
I think that's the one that was provided by @tomangelo2 (correct me if I'm wrong). I'll try to get it to compile when I have some time. Until then, 64bit should work (as long as the OS supports it)

**Comment by archeYR** [comment]
Ok, thank you.

**Comment by archeYR** [comment]
Hi, I have tested 64 bit build on Windows Professional x64, and there is another issue:
![virtualbox_windows xp x64_08_01_2018_23_35_37](https://user-images.githubusercontent.com/32551254/34695873-cc91bf00-f4cc-11e7-8310-06c6cc4e98ae.png)
But I have also tried newest 32 bit dev build, and it works fine:
![windows xp professional-2018-01-08-23-44-36](https://user-images.githubusercontent.com/32551254/34696167-0bebadc2-f4ce-11e7-9aa7-afc6a8934018.png)
If you want me to test 64 bit dev build, please give me binaries.

**Comment by tomangelo2** [comment]
Working x86 dev build proves that the issue is in the compilation method. Dev builds are compiled by MXE cross-compiler, while 0.1.11 release was compiled by MSYS2 environment.
We need to check if our traditional release compilation pipeline does still support Windows XP, I'm not sure but I think that previous releases were build by MSYS2 too, it might be matter of configuration, or it got an update between 0.1.10 and 0.1.11 releases that caused dropping Windows XP support.

**Comment by Skywalker13** [comment]
IMHO you should drop support of deprecated OS without security updates.

**Comment by archeYR** [comment]
@Skywalker13 Why? This game does not really need anything more. There is no real reason to drop support for Windows XP.

**Comment by Skywalker13** [comment]
You should not use WinXP anymore; It's full of security holes.

**Comment by archeYR** [comment]
@Skywalker13 I'm using Windows XP in virtualized environment for testing purposes only. Anyway, I still don't see any reason for dropping Windows XP support, it would be understandable if it actually needs anything from the newer systems.

**Comment by Skywalker13** [comment]
In general, when it's necessary to spend time and effort for supporting obsolete and buggy things then it's a very good reason to stop in order to work on real useful parts.

It's just my opinion..

**Comment by Erihel** [comment]
@archeYR WindowsXP is old. If it's only bulding and testing for Windows XP, maybe you can do it? I think guys would be glad if someone would help them with that.

On the subject of supporting old OS. If any library that Colobot uses does not work under Windows XP then what? If there's a graphic problem, is it Colobot bug or graphic driver problem? If it's driver problem it probably won't be fixed. Should Colobot try to make a workaround? I think it would be a waste of time.

**Comment by archeYR** [comment]
@Erihel I agree, but it is just matter of compilation, why would you compile your software for Windows Vista, if it can run on Windows XP just fine? I said above why Windows XP should be supported, and it's just my opinion. I understand that project's resources are very limited and I'm not demanding anything. If team decides to not support Windows XP, I'm fine with this.

**Comment by RaptorParkowsky** [comment]
Leaving WinXP indeed wasn't intended. And I think it should still be supported for few years or so. Windows isn't Linux (duh!) and is developed and distributed under different rules (duh! x2), so I think it should be supported relatively longer than any other OS due to it's popularity.

I wouldn't mind if any particular OS have more or less security holes. To be honest there's no OS without them. And our software isn't any high-security demanding banking application, web browser etc. It's just a game and don't require high-security environment to run I guess. Correct me if I'm wrong.

**Comment by Erihel** [comment]
Leaving any OS is not intended. Colobot uses libraries that work on many platforms to ease development process by handling OS differences. Does Windows XP have a separate build or there's only two builds for all Windows (32bit and 64bit)?

Side note: Clang, one of the leading C++ compilers dropped Windows XP support in 2015.

**Comment by archeYR** [comment]
@Erihel There are only two builds (x86 and x64) for all Windows versions.

**Comment by MrSimbax** [comment]
If any of the libraries or major tools Colobot uses drops support for Windows XP, then Colobot drops the support for it too. Simple as that. It probably hasn't happened yet, so I see no reason for dropping the Windows XP support right now, but it might happen any time in the future.

If I understand correctly, there is no issue with dev builds (MXE), but there is a problem with MSYS2 official builds. Apparently, it doesn't support Windows XP anymore, which explains the issue: https://sourceforge.net/p/msys2/mailman/message/35191999/

Why official builds can't be done with MXE anyway? Well, if not, then there is another alternative: in MSVC, building a binary with Windows XP compatibility requires only an additional flag, so official Windows builds could be done with that. Another alternative is the classic MinGW/MSYS configuration, if  it still supports Windows XP that is.

**Comment by tomangelo2** [comment]
I'm currently setting up virtual machine with Windows XP, hopefully we'll finally actually know what caused problem and then we'll think about possible solutions.

**Comment by archeYR** [comment]
@MrSimbax By the way, is there any reason why you can't stay on MSYS 2.5.1?

**Comment by MrSimbax** [comment]
I guess that's a solution too, although personally I try to avoid staying on old versions of software.

**Comment by tomangelo2** [comment]
Well, everything works, I've compiled both dev and master, as Debug and Release and every build worked on XP. Probably there was some incompatibility in specific version of msys or gcc I was using back then that caused this problem.

**Comment by archeYR** [comment]
@tomangelo2 Great. Are you going to rerelease a 0.1.11 version with hotfix? Or wait for the next release?

**Comment by tomangelo2** [comment]
Actually working on patch for XP.

**Comment by archeYR** [comment]
Tried with the latest version.
![virtualbox_windows xp_08_06_2018_20_05_18](https://user-images.githubusercontent.com/32551254/41173480-63c2fb5e-6b57-11e8-86f5-f2b39514722e.png)

Latest dev build works fine.

**Comment by tomangelo2** [comment]
As for that my patch that in the end didn't went live - I got working build, but there were another issues with it, then I had no spare time to get this to work, and finally I forgot about it. My fault.
Now about this problem - it seems like some library used by MSYS/gcc calls OS function that XP just doesn't have in its API. I guess as long as we use MSYS to get release build, we cannot do official builds supporting XP anymore, so support for this OS needs to be dropped (at least unless someone will find a way to bring it back). Dev builds might still work, we won't force it to break it, we just cannot promise that future builds will still keep compatibility with Windows XP.
Maybe there will be special last Release build for Windows XP, but I can't really tell if and when it'll be done.

**Comment by archeYR** [comment]
Is there any particular reason why MSYS is used for release builds?

**Comment by tomangelo2** [comment]
Probably because it's easier to build them on actual Windows instead of setting virtual machine or rebooting to Linux.

**Comment by JeanPaulLucien** [comment]
Without Windows XP support this Colobot will be not Colobot.

**Comment by tomangelo2** [comment]
Like it was mentioned, it's about compilation environment. It's not like we specifically moved with our tools to drop the support for XP, it's just not worth it for us to limit ourselves with older tools that won't be as efficient or capable as modern ones.
Msys support for XP is long dropped and it's outside of our control, mxe was dropped because of extra maintenance needed to fix its issues, modern VisualC++ versions probably don't support it either. Anyone can try to make it work on compiler supporting XP, but with our already limited possibilities to push things around it's just too hard to put extra time to make sure everything works on older OS's, or to keep ancient software versions.

**Comment by JeanPaulLucien** [comment]
@tomangelo2 I can attract (potential) developers, but I can be a project manager and create roadmap. If you know somebody who 

Else, what about to try to compile using other IDE? MSVS? Windows XP SP3 supports 2015.

Else. I know that the original game worked on Windows XP SP1 or even XP without SP. Now software make with SP3 support only. I'm not expert there and don't know reasons why drops previous SP and clear XP.

**Comment by tomangelo2** [comment]
Different OS's have different libraries. Newer ones got updated ones, with some functions added/changed/removed. Compilers use these functions to make a program. That's one of reasons for dropping support by them, in most cases it's just more profitable to make better binaries for up-to-date software, than for legacy ones. 
Same thing applies to libraries used by engine. Once they're compiled with calls to OS functions present from let's say Vista upwards, they'll refuse to work on XP, because it lacks these few functions.

If Visual 2015 still supports XP, then it might be possible to build such binary, as long as it supports Cmake projects and supports everything needed by code. I'm not really familiar with this environment, so I can't guarantee it.

**Comment by JeanPaulLucien** [comment]
@MrSimbax 
You are stange. You left when somebody who can help has appeared.

**Comment by tomangelo2** [comment]
If that person can help, they're free to build it, test it and do whatever they like to do, as long as it complies with the license. It's an open source project after all. There is no hard lock in the code against using XP as well, it just happens that modern compilers are going forward and drops outdated OSes. MSYS2 is going to break compatibility with Windows 7/8 next year, which will probably make us drop support for them as well, if Visual Studio will follow suite.
We physically cannot promise we're going to keep using outdated tools that still supports XP to publish official builds. Especially if it would make further development harder than it already is, due to some features not supported by older compilers and extra time needed to set up the environment. We cannot publish someones binaries as official, due to security risks, as stated above, and verifying if the binary is secure requires extra resources on our side.
As the issue is about official builds not supporting Windows XP, it got closed, as it's unlikely at the moment to make them XP-compatible again.

**Comment by MrSimbax** [comment]
> You are stange. You left when somebody who can help has appeared.

So you come here, demanding from us a Windows XP compatible binary for free, and when told _why_ we're not going to provide one, given quite a lot of technical explanations and arguments, you just decide to answer a month later with two sentences, of which one is an insult calling me "strange", and the second is some ridiculous lie, because I definitely didn't leave (whatever _that_ is supposed to mean in this context) and no help appeared regarding this issue (there only appeared, at most, empty _promises_ of help).

Let me make some things clear.

1. The issue is closed because no current maintainer wants to produce Windows XP binaries.
2. Everybody can try to produce such binaries. They can even be shared as long as they are compliant with the GPLv3 license and do not use the name "Colobot".
3. We do not guarantee that creating such a binary is possible without changing the current source code.
4. Whether pull requests with such changes will be accepted or not shall be decided on a case-by-case basis by code review process, as with all pull requests.
5. If a contributor decides to share such a GPLv3 compliant binary with us, we *might* add it to our download site, preferably after verification that the binary is safe, without unnecessary changes, and based on correct repository revision.

**Comment by JeanPaulLucien** [comment]
@MrSimbax I asked somebody to give me the link where I can download the binary to start test. I have seen 64-bit version. It will not work on 32-bit.

**Comment by tomangelo2** [comment]
There aren't any official 32-bit builds. There was no time for us to build and test 32-bit builds when we were preparing update, and - according to Steam Hardware Survey - 32-bit OSes market share is about 0.27% and keeps declining, making it not worth it for us to support them. Even if the number would be more in favor outside of Steam, I doubt that it reaches much more than that.
There are compilation instructions available in this repository, it's possible to try and build them for anyone to play. But there are no official builds, and I'm not sure if they'll be available again soon.

**Comment by JeanPaulLucien** [comment]
@tomangelo2 just is fact. Steam does not support 32-bit OS. Steam stats is incorrect. Steam has dropped 32-bit OS support in 2020.
