### ISSUE TITLE
Unselectable objects should not obey instructions from your bots

### ISSUE THREAD

**Issue by rbcat** [colobot/colobot#1217]
For example, you are still able to use factory() instruction on BotFactory with selectable=0, even though purpose of the later is obviously not to simply make an object unselectable, but not usable at all. Same goes for others objects, such as ExchangePost.

**Comment by Emxx52** [comment]
Oh no, they absolutely _should_. 
Otherwise many levels would potentially break. Moreover, to keep the game consistent, everything else would have to be adjusted accordingly (for instance accessing object parameters, radar(), etc.), making certain levels (most notably every single mission on Crystalium) _really_ tedious.

_Not selectable != not usable._ We could create a new Scene parameter for just that, though I don't really see the point rn.

**Comment by immibis** [comment]
@Emxx52 the issue is not "undetectable" but "uncontrollable"
