### ISSUE TITLE
Alpine linux compilation error when creating the binary

### ISSUE THREAD

**Issue by sodomon2** [colobot/colobot#1266]
I have an error when I finish compiling when I create the binary this is the error

[here is the log](https://github.com/colobot/colobot/files/4639672/log.txt)

**Comment by immibis** [comment]
`-lintl` is probably needed on this platform

**Comment by MrSimbax** [comment]
Looks like a problem with linking `gettext`. I assume this OS is detected as Linux so the following lines are executed https://github.com/colobot/colobot/blob/0a3cdd342bf786d2798d0225e8397a7f3b45adcb/src/CMakeLists.txt#L100-L102
Therefore we wrongly assume that the `intl` library is linked automatically on every Linux platform. Hopefully this issue will be fixed in the `dev-modern` project.

In the meanwhile, you could try adding `-DCMAKE_CXX_STANDARD_LIBRARIES="-lintl"` to the CMake command line arguments.

**Comment by sodomon2** [comment]
Oh,thanks for the help now if you compile without errors from gettext,now I will close this 😁
