### ISSUE TITLE
Ground spots not rendered by default on fresh player profile

### ISSUE THREAD

**Issue by MrSimbax** [colobot/colobot#1280]
Ground spots and underground resources (from the debug menu) are not rendered at all on fresh Colobot install (by "fresh" I mean no `saves` folder, new user profile, not a single graphics setting changed).

After quick experimentation I discovered it is caused by a specific combination of settings in the `colobot.ini` file:

```
Anisotropy=1
MipmapLevel=1
FilterMode=1
```

Changing any of these options to a value other than `1` causes the ground spots to render.

It looks like a problem with the default values upon creation of the `colobot.ini` file. Even change to the "Lowest" graphics settings in the options menu causes the ground spots to render.

**Comment by hexagonrecursion** [comment]
I can reproduce this issue.

* This appears to be the same issue as #976

I am not sure which video card the game is using:
```
00:02.0 VGA compatible controller: Intel Corporation 4th Generation Core Processor Family Integrated Graphics Controller (rev 06)
01:00.0 VGA compatible controller: NVIDIA Corporation GK107 [GeForce GT 740] (rev a1)
```
Graphics settings: [colobot.json](https://github.com/user-attachments/files/16646521/colobot.json)
colobot version: dev (36ab303f66a428f76c1e3895e4d2cff8f72b1b55)
Guest (container): debian_version trixie/sid
Host: Fedora release 40 (Forty)
distrobox: 1.7.2.1

**Comment by hexagonrecursion** [comment]
I see what is happening

1. shadow00.png, shadow01.png, ..., shadow15.png are textures that are generated by the game and only exist in memory. they do not exist as files
2. [CTerrain::CreateMosaic](https://github.com/colobot/colobot/blob/b2a0deaabb8b6fd256a3cdd54057b03bca388e90/colobot-base/src/graphics/engine/terrain.cpp#L576) creates a material with detailTexture=shadow00.png (same for the other 15)
3. This causes CEngine::LoadAllTextures to try to read textures/shadow00.png because the texture have not yet been generated
  https://github.com/colobot/colobot/blob/b2a0deaabb8b6fd256a3cdd54057b03bca388e90/colobot-base/src/graphics/engine/engine.cpp#L1997
1. This causes textures/shadow00.png t become blacklisted
  https://github.com/colobot/colobot/blob/b2a0deaabb8b6fd256a3cdd54057b03bca388e90/colobot-base/src/graphics/engine/engine.cpp#L1881
1. CreateOrUpdateTexture(textures/shadow00.png) becomes a no-op
1. CEngine::UpdateGroundSpotTextures can't add textures/shadow00.png to the cache because CreateOrUpdateTexture(textures/shadow00.png) is a no-op
  https://github.com/colobot/colobot/blob/b2a0deaabb8b6fd256a3cdd54057b03bca388e90/colobot-base/src/graphics/engine/engine.cpp#L4048

**Comment by hexagonrecursion** [comment]
The reason the workaround of changing Anisotropy, MipmapLevel or FilterMode works is that the variables are always initialised to 1, 1 and BILINEAR. 

https://github.com/colobot/colobot/blob/b2a0deaabb8b6fd256a3cdd54057b03bca388e90/colobot-base/src/graphics/engine/engine.cpp#L247-L248
https://github.com/colobot/colobot/blob/b2a0deaabb8b6fd256a3cdd54057b03bca388e90/colobot-base/src/graphics/engine/engine.cpp#L281
https://github.com/colobot/colobot/blob/b2a0deaabb8b6fd256a3cdd54057b03bca388e90/colobot-base/src/graphics/engine/engine.cpp#L284

After the variables are initialized, but before CEngine::LoadAllTextures() triggers the bug, a function called CSettings::LoadSettings() calls CEngine::SetTextureAnisotropyLevel() CEngine::SetTextureMipmapLevel() and CEngine::SetTextureFilterMode(). This three functions call ReloadAllTextures(), but only if the value loaded from the config differs from the current value of the variable.

https://github.com/colobot/colobot/blob/b2a0deaabb8b6fd256a3cdd54057b03bca388e90/colobot-base/src/graphics/engine/engine.cpp#L2421-L2430
https://github.com/colobot/colobot/blob/b2a0deaabb8b6fd256a3cdd54057b03bca388e90/colobot-base/src/graphics/engine/engine.cpp#L2406-L2414
https://github.com/colobot/colobot/blob/b2a0deaabb8b6fd256a3cdd54057b03bca388e90/colobot-base/src/graphics/engine/engine.cpp#L2392-L2399

CEngine::ReloadAllTextures() calls UpdateGroundSpotTextures(), which generates the shadow textures and puts them in the cache

When LoadAllTextures is called the game does not try to find the file named textures/shadow00.png because the generated textures are already in the cache. This prevents the bug from being triggered

**Comment by hexagonrecursion** [comment]
I have tracked this down to a bug in CEngine::DeleteAllGroundSpots()

Should be "textures/shadow" instead of "shadow":
https://github.com/colobot/colobot/blob/b2a0deaabb8b6fd256a3cdd54057b03bca388e90/colobot-base/src/graphics/engine/engine.cpp#L1351

The full event chain in chronological order:

1. m_textureMipmapLevel, m_textureAnisotropy, m_defaultTexParams.filter and m_terrainTexParams.filter are initilized
1. CSettings::LoadSettings() does not cause CEngine::ReloadAllTextures() to be called because the values from the config file match the initial value of the variables
1. CEngine::DeleteAllGroundSpots() creates a texture named shadow00.png instead of textures/shadow00.png
1. CTerrain::CreateMosaic() adds a material that uses textures/shadow00.png
2. CEngine::LoadAllTextures() tries to read the file named textures/shadow00.png, fails and the texture is blacklisted
3. CEngine::UpdateGroundSpotTextures() calls CreateOrUpdateTexture("textures/shadow00.png"), but this is a no-op
