### ISSUE TITLE
Warning : deprecated way to define scene 

### ISSUE THREAD

**Issue by CozmoCyke** [colobot/colobot#1281]
I try the colobot-logic level ,

[INFO]: Loading level: levels/custom/chapter001/level003/scene.txt
[WARN]: This level is using deprecated way of defining %1$s scene. Please change the %1$s= parameter in EndingFile from %2$d to "levels/other/%1$s%2$03d.txt".
[WARN]: This level is using deprecated way of defining %1$s scene. Please change the %1$s= parameter in EndingFile from %2$d to "levels/other/%1$s%2$03d.txt".

scene.txt contained this file:
EndingFile win=2 lost=0

I don't understand what I have to change to avoid the deprecated way !
Windows 10 , Colobot Gold , official 0.1.12-alpha build

**Comment by Emxx52** [comment]
Wrong repo, report this issue here: https://github.com/badernageral/colobot-logic

Currently this is just a warning - you may ignore it. This custom level is just old and should be updated.

If you really want to fix it yourself you can replace `EndingFile win=2 lost=0` in Scene with `EndingFile win=002 lost=0`

**Comment by CozmoCyke** [comment]
Thank you. I'll try to apply these changes

**Comment by melex750** [comment]
In 25004757 the EndingFile command was extended to accept filenames.

The solution to this issue might be something like this:
```
EndingFile win="levels/other/win002.txt" lost="levels/other/lost000.txt"
```
It looks like the strings can use ```%lvl%```, ```%cat%```, and ```%chap%``` shortcuts too.
