### ISSUE TITLE
WayPoint is white

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#131]
![Przechwytywanie](https://f.cloud.github.com/assets/1517255/173252/019b35c0-7ad7-11e2-84f6-84ae8ef43d35.PNG)

**Comment by krzys-h** [comment]
On GL2.1 engine they look ok, but still slightly lighter than originals. This is most likely a lighting bug in GL1.4 engine.
![image](https://cloud.githubusercontent.com/assets/1517255/13029316/5b4f78ee-d289-11e5-8019-f76687476836.png)

**Comment by RaptorParkowsky** [comment]
As @OdyX earlier said, this is definitely the game's lightning problem that appear to influent globally in the game. Every object rendered in GOLD looks too bright comparing to original Colobot. You can't even notice any shading on the models faces because of this. And of course, objects that have faces without assigned textures but only diffuse color are most noticeable to be brigher than it should be.

**Comment by krzys-h** [comment]
Fixed in 9c32f705b615d210de99bfa1e8225ad2dbc5ce76
