### ISSUE TITLE
Game crash when loading SatCom

### ISSUE THREAD

**Issue by tomangelo2** [colobot/colobot#1356]
```[TRACE]: System event EVENT_KEY_UP:
[TRACE]:  virt    = false
[TRACE]:  key     = 1073741882
[TRACE]:  rTime = 0.000000
[TRACE]:  kmodState = 1000
[TRACE]:  mousePos = 0.000000, 0.000000
[TRACE]:  mouseButtonsState = 00
[TRACE]:  customParam = 0
[DEBUG]: Deactivated pause mode - engine|hide_shortcuts
[TRACE]: Reset key states
[DEBUG]: Activated pause mode - engine|hide_shortcuts|mute_sound|camera
[TRACE]: Opening SDL memory wrapper for file '/fonts/dvu_sans.ttf'
[DEBUG]: Loaded font file /fonts/dvu_sans.ttf (font size = 19.2)

Unhandled exception occurred!
==============================
Type: std::invalid_argument
Message: Unexpected UTF-8 continuation byte
==============================

This is usually caused by a bug. Please report this on http://github.com/colobot/colobot/issues
including information on what you were doing before this happened and all the information below.
==============================
You seem to be running a custom compilation of version git-dev~rb17a4391, but please verify that.

The game was in phase PHASE_SIMUL (ID=8)
Last started level was: category=missions chap=1 rank=2
==============================

Sorry for inconvenience!
[Thread 3776.0x2660 exited with code 1]
[Thread 3776.0x27d8 exited with code 1]
```
There is no backtrace available, It happens on any language except English.

Edit: Long log with steps between last log line and error here: https://pastebin.com/dNGif37R
Edit_2: It happened during mission 1.2, but it doesn't happen on 1.1 and 1.3.
Edit_3: On other planets it also happens "randomly". 2.1 and 3.3 are affected by it, but other Moon and Tropica missions are good.
Edit_4: Blaming @MrSimbax for breaking it, git bisect pointed this commit https://github.com/colobot/colobot/commit/7449111a00c7e62a898f54d3c59dcefe6b307ead#diff-39d9ebe680a2aa2cdcb487e420d1d7de as first bad one. I've checked commit before that one https://github.com/colobot/colobot/commit/6c715ffef9f2323f7134b1252f92bac36caaf6f7 and it works.

**Comment by MrSimbax** [comment]
Similar issue has been already discussed in the team internally a while ago and the commit is apparently correct at least according to the UTF-8 specification, so something fishy happens with the char string before the length function is called but without backtrace it'll be hard to find the source of the bug. I thought the crashing was fixed in https://github.com/colobot/colobot/commit/a5c718701779096d214a9afca50206eb474da00a especially that the fixes were tested by at least one other person so I guess there's more places in the code that need to be fixed.
