### ISSUE TITLE
Building Buzzingcars

### ISSUE THREAD

**Issue by 4VRDriver** [colobot/colobot#1382]
Hello,
Buzzingcars was one of my favorite childhood games. I would love to build it from the dev-buzzingcars branch.
I've built that branch and it all compiled fine, but when launching it seems like it launches not Buzzingcars but Colobot. After a few seconds it crashed.
I built Buzzingcars using the INSTALL.MD instructions. I'm on Linux if that is from interest.

Thanks for your help.

**Comment by tomangelo2** [comment]
Hello
The port of Buzzing Cars is still far from ready. Colobot engine doesn't support all the features required by BC, meanwhile reapplying all the changes required to make original code works is a lot of unnecessary work that we'd rather avoid by porting BC features to our engine and let both games run from same code. Since it requires redesigning some parts of code to support simultaneously Colobot, BuzzingCars and Blupimania 2 (which will be ported in future as well) on top of making already existing code easy to further develop, I'd say we're far from making it actually work.
Another point is that BuzzingCars isn't our priority at this point, there is still so much to do with Colobot itself, so at this moment only way to play BuzzingCars is to download original game from blupi.org, set up compatibility mode with Windows XP and it should work.

**Comment by 4VRDriver** [comment]
I see, thank you!
