### ISSUE TITLE
Add the ability to give commands to robots without programming

### ISSUE THREAD

**Issue by X64E** [colobot/colobot#1566]
Programming in C is quite boring and sometimes you want some kind of convenient control.
For example, to have a special panel on which you can set the percentage of the battery at which the robot will fly to the power station. Or the percentage of damage when the robot flies for repairs. You can also specify what to take the robot and where to put it. For example, ore to a converter and place titanium around converter. Or for a combat robot to destroy targets without a program. And so on.

Such a panel should look simple and intuitive, like this:

![изображение](https://user-images.githubusercontent.com/95232774/227717561-72bbfe76-2107-425d-9706-1dc86ff3841e.png)

**Comment by LosephCawtonJurtis** [comment]
I feel like abstracting away the functions of the robots to this degree without any programming would kind of defeat the purpose of the game :/ like you're referring to the much of the major functionality of the robots meaning that all of the programs to be written would be for far more specific tasks and would kind of take the whole programming element away from the focus(which it absolutely should remain as)

However! I would love a command or something that allows you to represent certain values in the GUI so you could tweak inputs on the fly instead of having to open the editor. like if you could bind `<% damage before return for repair>` to a slider on the robot's GUI, that would be very cool. I like the interface you've designed I just think it should still be something that you have to build your self in-game, but that would be an extremely cool quality of life feature.
