### ISSUE TITLE
Lack of M1 builds

### ISSUE THREAD

**Issue by tomangelo2** [colobot/colobot#1574]
There are still no Apple ARM CPU builds in GitHub Actions.

GitHub hosted M1 builds will be available in Q4 2023 https://github.com/github/roadmap/issues/528

**Comment by hexagonrecursion** [comment]
github actions now support M1 - [both macos-14 and macos-15 runners use M1 according to the docs](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories).

* Implementation of this issue is blocked by https://github.com/colobot/colobot/issues/853

**Comment by hexagonrecursion** [comment]
* Fixed by https://github.com/colobot/colobot/pull/1794 - added macos-14 and macos-15 runners
