### ISSUE TITLE
Taking off while Program Editor is opened softlocks the game

### ISSUE THREAD

**Issue by dark-steveneq** [colobot/colobot#1592]
When you take off from a program while the Program Editor is opened softlocks the game completely, window controls won't do anything and so does Escape key. Possible fixes for this I came up with include the game forcefully closing the Program Editor, waiting with the cutscene until the player closes the editor and termination of the program that started the cutscene. In my opinion, the last option is the best, since the first option could lead to lost progress and in the second one the player could miss a notification or something else that would tell them that they need to close the window to proceed.

**Comment by hexagonrecursion** [comment]
CAutoBase (the spaceship animation) gets stuck in phase ABP_CLOSE2 because m_engine->GetPause() is true

https://github.com/colobot/colobot/blob/b2a0deaabb8b6fd256a3cdd54057b03bca388e90/colobot-base/src/object/auto/autobase.cpp#L135

This script softlocks:
```c++
extern void object::New()
{
	takeoff();
}
```

This script does not:
```c++
extern void object::New()
{
	takeoff();
	while(true);
}
```

If the studio interface is open and the script is not running (e.g. it exited), the studion pauses the engine:

https://github.com/colobot/colobot/blob/b2a0deaabb8b6fd256a3cdd54057b03bca388e90/colobot-base/src/ui/studio.cpp#L358-L372

**Comment by hexagonrecursion** [comment]
Window controls won't do anything because the bot is no longer selected (was deselected by CAutoBase::TakeOff)

https://github.com/colobot/colobot/blob/b2a0deaabb8b6fd256a3cdd54057b03bca388e90/colobot-base/src/ui/object_interface.cpp#L237-L238
