### ISSUE TITLE
RemoveComments can go out of bounds

### ISSUE THREAD

**Issue by PatrickvL** [colobot/colobot#1614]
When the last character of a string gets checked and is a forward slash, the subsequent character check will read the string array out of bounds (which might cause an exception).

**Comment by tomaszkax86** [comment]
[Are you sure about that?](https://en.cppreference.com/w/cpp/string/basic_string/operator_at)
>Returns a reference to the character at specified location pos if pos < size(), or a reference to CharT() if pos == size(). No bounds checking is performed.

**Comment by PatrickvL** [comment]
That same page states "No bounds checking is performed. If pos > size(), the behavior is undefined."
So it might cause an exception, depending on the implementation and per case the memory layout

**Comment by PatrickvL** [comment]
Also this got introduced with the merge of the recent pull request - before that this risk wasn't there.

**Comment by tomaszkax86** [comment]
The code doesn't go above size() so it will never fail, it will at most read std::string's terminator character `'\0'`. Also, this cannot cause an exception because it's not at().

If you want to submit a pull request where the range iterated over goes to `size() - 1`, feel free to do so. Other than skipping one iteration it won't actually fix anything because there no bug, technically.

**Comment by hexagonrecursion** [comment]
I agree with @tomaszkax86 - the code was confusing, but not broken because `string[string.size()]` is guaranteed to return `char()` (i.e. `'\0'`) if `string` is `std::string`. Nonetheless 3433b9590a36545d32d612c2221e1c95c8604ea0 changes the code to be less confusing. This issue can be closed now

**Comment by tomaszkax86** [comment]
Addressed in 3433b9590a36545d32d612c2221e1c95c8604ea0
