### ISSUE TITLE
Crash upon loading crashsave

### ISSUE THREAD

**Issue by Zemogiter** [colobot/colobot#1678]
So I was playing mission 9-4 of ReturnBot and when I was processing uranium, the game crashed. Log file in `/home/username/.local/share/colobot` is empty. I tried loading in the crash save and it crashed, again with empty log file:
```
Unhandled exception occurred!
==============================
Type: CLevelParserException
Message: Failed to open file: ../../crashsave/data.sav
==============================

This is usually caused by a bug. Please report this on http://github.com/colobot/colobot/issues
including information on what you were doing before this happened and all the information below.
==============================
You seem to be running a custom compilation of version git-dev~rc56d240a, but please verify that.

The game was in phase PHASE_PLAYER_SELECT (ID=3)
Last started level was: category=exercises chap=0 rank=0
==============================
```

**Comment by hexagonrecursion** [comment]
I have bisected this regression down to 4dc051a95e7c76e0be8b4b74fe30b086ca096b44.

**Comment by hexagonrecursion** [comment]
1. There was a bug causing `CResourceManager::CleanPath()` to turn "../../crashsave/data.sav" into "crashsave/data.sav"
2. The bug was masking another bug - the path to crashsave was specified incorrectly
3. 4dc051a95e7c76e0be8b4b74fe30b086ca096b44 fixed bug 1 and now the bug 2 is no longer hidden.

I'll submit a fix today.
