### ISSUE TITLE
Use of 'object::' notation in CBot for other classes

### ISSUE THREAD

**Issue by tomaszkax86** [colobot/colobot#207]
It is possible to abuse 'object::' notation used for accessing bot parameters in functions. You can do so by creating new class and using this class's name instead of 'object'. This will give you access to class's attributes like they were declared variables. These attributes are actually bot's parameters like category, position, orientation etc., but with different types and names. Attempt to modify them may result in crashing the game.

```
extern void object::CrashGame()
{
    crash();
}

public class Crasher
{
    int x;
    float y;
}

void Crasher::crash()
{
    y = 0;    // this crashes the game
}
```

**Comment by krzys-h** [comment]
The game now doesn't allow to use other classes in the object:: notation
Out of class declaration will be implemented later

**Comment by melex750** [comment]
CBotFunction::DoCall()
CBotFunction::CompileCall()

both functions call:

CBotFunction::FindLocalOrPublic()

which starts with this --->TypeOrError.SetType(CBotErrUndefCall);

maybe this function can be modified to find only

   object::function
   thisfunction->thisclass::function
   noname::function


maybe put something like this at the begining of the three
"for loops" in CBotFunction::FindLocalOrPublic()
```c++
    if(pt->m_MasterClass != this->m_MasterClass &&
       pt->m_MasterClass != "object"            &&
       pt->m_MasterClass != ""                    ) continue;// skips it
```

Then the code in the OP would not compile: CBotErrUndefCall,
but if it did compile, CBotFunction::DoCall() 
would miss it's mark, which throws no error.

I think it might work properly then, i could be wrong.

**Comment by krzys-h** [comment]
I'm planing to refactor this code soon, I'll take a look at this then. The problem is that the code always assigns "this" to the robot that is executing the program for functions that are outside of classes, near the code I changed in CBotFunction::DoCall
You definetly can't hardcode the string "object" inside the CBot engine as that's defined by Colobot, not the programming language structure.

**Comment by melex750** [comment]
oh.  i though "this" in c++ context referred to this instance of CBotFunction. oops.

i figured that about "object", i didn't know what the actual reference should be.

**Comment by krzys-h** [comment]
If we really need to know what the passed "object" type is:
```C++
stack->GetBotCall(true)->m_thisVar->GetClass()->GetName()
```
But that doesn't really solve our problem

PS. I'm renaming GetBotCall to GetProgram in next commit so don't be suprised if you'll be looking for it ;)

**Comment by melex750** [comment]
It turns out that sometimes "this" is correct and sometimes not.
Basically, if you define the class and function above the extern function, it mostly works.
If you put the function above the class, it always works.

Anything below the extern function is mostly broken.  Similar to issue https://github.com/colobot/colobot/issues/672
Removing "public" from the function, generally has a negative effect as well.
"this" seems to be created in the context of the call and not the object being called.

A possible solution could be to implement forward declarations denoted by a semi-colon,
to be used as intermediate pointers to functions and classes.

I tested "this" with this program on a version prior to commit 0807b75:
```c++
/////////////////////////////////////
public void Top::beforeT()
{
    message(""+this);
}
/////////////////////////////////////
public class Top
{
    void insideT()
    {
        //this.beforeT(); // pointer to Top
        beforeT();        // pointer to Top
        afterT();         // pointer to object
        //this.afterT()   // no compile 
    }
}
/////////////////////////////////////
public void Top::afterT()
{
    message(""+this);
}
/////////////////////////////////////////////////////  Main
extern void object::MainTest()
{
    Top top();
    top.insideT();    // see Top
    top.beforeT();   // pointer to Top
    top.afterT();    // pointer to Top
    //beforeT();       // pointer to object<--i think these should not compile
    //afterT();        // pointer to object<--

    Bottom bottom();
    bottom.insideB(); // see Bottom
    bottom.beforeB();// no compile
    bottom.afterB(); // no compile
    //beforeB();       // pointer to object<--i think these should not compile
    //afterB();        // pointer to object<--
}
/////////////////////////////////////
public void Bottom::beforeB()
{
    message(""+this);
}
/////////////////////////////////////
public class Bottom
{
    void insideB()
    {
        //this.beforeB();  // pointer to bottom
        beforeB();       // pointer to bottom
        afterB();        // pointer to object
        //this.afterB();   // no compile
    }
}
/////////////////////////////////////
public void Bottom::afterB()
{
    message(""+this);
}
/////////////////////////////////////
```
