### ISSUE TITLE
Freeing memory from unused class instances

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#371]
Should be probably fixed along with #257
Discussion: http://colobot.info/forum/viewtopic.php?f=21&t=699&view=unread#unread

**Comment by krzys-h** [comment]
I'm pretty sure this is still an issue. Just do this and watch colobot memory usage grow, then stop the program - it'll drop a bit but most of the memory stays allocated

```C++
public class test {
	public int array[10000];
	
	public void test() {
		array[9999] = 0;
	}
}

extern void object::Nowy()
{
	test[] t;
	while(true){
		t[sizeof(t)] = new test();
		wait(0); // see #971
	}
}
```

**Comment by hexagonrecursion** [comment]
stop the program - it'll drop a bit but most of the memory stays allocated

* same issue: #1761

**Comment by melex750** [comment]
I forgot about this. I basically get the same results as second post, but if I let the memory usage grow above 250MB and then stop the program, it'll drop back down close to where it started.

Maybe the OS sometimes keeps some memory in reserve for the program that was just using it.  Maybe this is platform dependent behavior.

**Comment by hexagonrecursion** [comment]
I have executed the above test case with LeakSanitizer. It detected some memory leaks - but all the leaks are from loading the game and compiling the program - running the program appears to produce no memory leaks.

---

I have executed a modified version of the program with silent breakpoints on `CBot::CBotVar::CBotVar()`, `CBot::CBotVar::CBotVar(CBot::CBotToken const&)`  and `CBot::CBotVar::~CBotVar()`. The breakpoint hit counts told me that the constructor was executed as many times as the destructor - no memory was leaked.

Note: the program had to be modified because breakpoints slowed the original code down too much.

```c++
public class test {
	public int array[10];
	
	public void test() {
		array[9] = 0;
	}
}

extern void object::Nowy()
{
	test[] t;
	t[sizeof(t)] = new test();
	while(true);
}
```

---

Two different methodologies. Both confirm that *executing* the program produces no memory leaks. If this bug ever existed, it has been fixed.

game version 890333ef972bff5c182c3c93e9087d77368f1f62
