### ISSUE TITLE
Circular class references (diffrent types) in CBot

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#433]
First, make a program with a class like this:
```C++
public class TestClass {
    int test;
}
```
Click OK in the editor and start the program once. Then, edit the program to look like this:
```C++
public class OtherClass {
    TestClass testclass;
}

public class TestClass {
    int test;
    OtherClass otherclass;
}
```
Everything compiles properly and works as expected.

Now, restart the game and try compiling the second program again. The game will refuse to compile it now, telling you that it doesn't know what TestClass is (in line 2).

**Comment by melex750** [comment]
This also happens when you type:
 ```java
public class OtherClass extends TestClass
```
A temporary workaround, short of moving TestClass above OtherClass
is to //comment out the offending instructions, click compile, uncomment
then it compiles ok. I may be easier to move TestClass in many cases.

This is due to being compiled from top to bottom,  Compile1 attempts to
simulate forward declarations, but fails because it also parses variables.

Functions also have a Compile1 for this purpose.

I ran Doxygen with GraphVis' Dot utility on the CBot Library.

This is one of many nice flowcharts showing how this works.
https://www.dropbox.com/s/uksguc8ar9fbwzc/CBotFunction.png

**Comment by cbot-coder** [comment]
I am still seeing something like this behavior, where if I have a class hierarchy, sometimes the subclasses fail to compile; workaround is to comment them out, then compile, then uncomment them and they compile. It seems the first time around it doesn't know about the parent class, but after commenting out child, it compiles parent class, and knows about it, so uncommenting child class now works. It's not just a simple top-down ordering issue though, because some classes work fine even if parent is declared below the child.
