### ISSUE TITLE
Code battles

### ISSUE THREAD

**Issue by ychoucha** [colobot/colobot#468]
Hello Colobot it"s just exelent, i really like !!

but can we use it in multiplayer please ?

**Comment by tomangelo2** [comment]
We will propably add multiplayer to our code, but for now we have more important things that need to be fixed or added. If our plans won't change we will add this in Beta.
Simple multiplayer is available even with current code (it's in colobot-mp branch), we have even video with test https://www.youtube.com/watch?v=4YRqMSv1SX0, but for now we're focusing on another jobs.

**Comment by microspace** [comment]
If there will be multiplayer, that we can start 'code battles' like in robocode http://robocode.sourceforge.net/. It will be very fun and challenging.
There can be other challenges, not just destroying each others bots. For example, race like formula-1 with pit-stops for recharging battaries.

**Comment by krzys-h** [comment]
"Code battles" would be possible even without multiplayer. Actually, I kinda like that idea - you set two programs against each other and make sure they are started at the same time. This would need an enhancement to radar() and object class to detect which "team" objects are on.
I have a nice idea for such a map: two players start with only one WheeledGrabber each, with their program, and have to build a factory of shooter bots in order to attach each other. It would be awesome, because the bots would have to make strategical decisions on what to attack first (e.g. you might decide to attack enemy BotFactory first so he cannot make new bots. Or, actually, maybe it would be more beneficial to destroy all grabbers first, so they cannot build anything AND they cannot make new bots?)

**Comment by ychoucha** [comment]
+1

**Comment by krzys-h** [comment]
Code battles are implemented now in the dev branch. We still don't have an official code battle level in the game yet.
