### ISSUE TITLE
Change and rename standard resolutions on the list in settings menu

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#501]
Add 320x240 (4:3 QVGA)
Rename 640x480 into 640x480 (4:3 VGA)
Rename 720x480 into 720x480 (3:2 NTSC)
Change 720x576 into correct 768x576 (4:3 PAL)
Rename 800x600 into 800x600 (4:3 SVGA)
Change 848x480 into correct 854x480 (16:9 WVGA)
Remove 960x600
Add 1024 x 576 (16:9 PAL)
Rename 1024x768 into 1024x768 (4:3 XGA)
Rename 1280x720 into 1280x720 (16:9 HD 720)
Rename 1280x768 into 1280x768 (5:3 WXGA)
Rename 1280x800 into 1280x800 (16:10 WXGA)
Add 1280x854 (3:2)
Add 1152x768 (3:2)
Rename 1152x864 into 1152x864 (4:3 XGA+)
Add 1366x768 (16:9 WXGA)
Rename 1280x960 into 1280x960 (4:3 SXGA−)
Rename 1280x1024 into 1280x1024 (5:4 SXGA)

Unfortunaltely I don't know, what resolutions are beyond this list and already work in GOLD settings menu (on my PC this is maximum), so I hope someone supplement this list. IMO the game should allow to set by game's UI every standard and available resolution, especially for 4:3, 3:2 and 16:9.

Proper standard names of the resolutions with aspect ratio can be useful for most users.

**Comment by krzys-h** [comment]
The list of resolutions is not actually set in the code, it's whatever your graphics driver provides as supported resolution list. For this reason, there is no such thing as "change into correct 768x576" or "add 1366x768" - your graphics driver doesn't recommend using that resolution, so you may notice a performance drop in such configuration. Remember, if you really want to force the game to use some weird resolution, you can use ***-resolution WxH*** commandline argument.
Also, if we really wanted the names to be displayed, we would need to hardcode them, and I don't think it's necessary to maintain such a list. I've never seen a game that added additional names to resolutions.
Showing the aspect ratio should be possible to implement without hardcoding available resolutions list, and might actually be useful since the UI scaling on anything that's not 4:3 is currently really terrible.

If you really want a full list in all configurations I can get (on Linux, I'm not sure if it's the same on Windows):
a) on a laptop screen, 1920x1080
1920x1080
1680x1050
1600x1024
1440x900
1400x1050
1360x768
1280x1024
1280x960
1152x864
1024x768
800x600
640x480

b) external monitor, 1280x1024
1280x1024
1280x960
1152x864
832x624
800x600
720x400
640x480

c) dual-screen
3200x1080
1280x1024
1280x960
1152x864
1024x768
832x624
800x600
720x400
640x480

**Comment by Erihel** [comment]
Aspect ratio is ok. Names doesn't mean anything to most users.

**Comment by RaptorParkowsky** [comment]
Well, I didn't know that those resolutions aren't hardcoded. So there's no need to hardcode them with their names. Only aspect ratio would be helpful to add.

**Comment by krzys-h** [comment]
Aspect ratio has been added so I'm closing this issue since we decided to not do the rest.
