### ISSUE TITLE
Game crashes at specific point during a code battle

### ISSUE THREAD

**Issue by CHmSID** [colobot/colobot#532]
When in krzys-h's battle code example level, the wheeled grabber from the red team attempts to create a powercell for the newly created shooter, the game crashes.

Steps to reproduce:
1. Start a free mission using krzys-h's level from #513 
2. Use ` to open cheat console and type "all", unless you have everything researched already.
3. Observe the red team create the converter, power plant, research center, factory, and a shooter.
4. When the robot attempts to create a power cell for the newly created shooter, the game will crash anywhere between the point of converting titanium ore to placing the titanium on the power plant.

**Comment by krzys-h** [comment]
Requirement to do "all" is probably another bug, could you create a new issue for that?

**Comment by CHmSID** [comment]
Yes, I can. I also found out that if the other team idles, the crash still occurs.

**Comment by krzys-h** [comment]
I'm guessing this is not the PowerCell, but the BotFactory finishing construction of a robot. Does that seem right?
Did you build the game yourself or used binaries from the build platform? What OS? Looks like the std::regex implementation might be different from mine, since everything works fine for me.

**Comment by CHmSID** [comment]
I'm on Ubuntu 14.04 and built Colobot 0.1.5+alpha-git-dev~rdfd7311 from source both as a Release and Debug. I'm using gcc 4.8.4 for compilation.

I thought it could be a problem with the BotFactory as well, but when checking it out, the game crashed when the progress bar was at about 85%. So i guess this excludes the BotFactory?

**Comment by krzys-h** [comment]
The progress bar gets to 100% when the doors are fully open. The crash probably happens when the doors start opening, that is when bot is finished and tries to start the program. It's possible that's 85%.
I don't know, your setup looks really similar to mime. Is your program exactly the same as my one included with the level?

**Comment by krzys-h** [comment]
From what I've read GCC 4.8 doesn't have full regex support, it has been fully implemented in 4.9. This should be probably changed to boost::regex.

**Comment by CHmSID** [comment]
I'll upgrade GCC and see what happens. I'm using the unmodified program you included with the level.

**Comment by piotrdz** [comment]
@krzys_h: Yes, that's most probably std::regex fault. I ran into the same problem before. Only using boost::regex is safe for all compilers that we support.

**Comment by CHmSID** [comment]
I can confirm that the game crashes only when it's compiled with gcc older than 4.9.
It did not crash with gcc 4.9.2, also the moment the game crashed was indeed when the message "New bot available" was displayed.

**Comment by krzys-h** [comment]
It shouldn't crash anymore since @piotrdz commited a fix already.
