### ISSUE TITLE
SecondTexture (dirt texture) doesn't work when quality shadow mapping is enabled

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#549]

**Comment by krzys-h** [comment]
Only with quality shadow mapping enabled

**Comment by krzys-h** [comment]
![image](https://cloud.githubusercontent.com/assets/1517255/9118190/0d908720-3c6f-11e5-925d-ccc0b4d0ae2b.png)
![image](https://cloud.githubusercontent.com/assets/1517255/9118212/32edd496-3c6f-11e5-9efa-5d960f434b96.png)

**Comment by tomaszkax86** [comment]
This problem exists only in OpenGL 1.4 engine. Shader based engines render dirt correctly. The only reliable way to fix it is to reorder bindings to texture units which would require a bit of hacking. There are two solutions:

1. Add alternative rendering path for OpenGL 1.4 engine
2. Refactor CDevice interface

I think the second part should be used. CDevice is currently too low level. Instead, it should only expose features needed for rendering. SetTexture() could be replaced by three methods: SetPrimaryTexture(), SetSecondaryTexture(), and SetShadowTexture(). CGLDevice would choose which texture is to be bound to which texture unit based on it's own settings. For quality shadows first two texture units would be used to calculate shadow value, 3rd one would be the primary texture and 4th would be the secondary texture. Other OpenGL engines would do what they currently do. We could also remove texture environment settings since they can be inside CDevice and not exposed to outside. As a result, CGLDevice class would only need 4 texture units to implement quality shadows, dirt would be fixed, and CDevice interface would be simpler.

**Comment by tomaszkax86** [comment]
Should be fixed by e6a2fc967149a6bb6096e5208f4d7d52fc0e200c
