### ISSUE TITLE
Creating colobot.ini in first start crashes the game

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#552]
The 2nd start, when colobot.ini is created, starts normally.

**Comment by krzys-h** [comment]
Could it be #522 again? I need to know which version is that and game logs.

**Comment by RaptorParkowsky** [comment]
Logs here: http://pastebin.com/JZiaizya

**Comment by krzys-h** [comment]
Could you also show the shadow mapping settings from colobot.ini? Both after first failed attempt (if anything gets created at all) and at the second one.

**Comment by RaptorParkowsky** [comment]
First run, with crash:
```
MipmapLevel=1
Anisotropy=1
ShadowColor=0.5
ShadowRange=0
MSAA=2
FilterMode=1
ShadowMapping=1
ShadowMappingQuality=1
ShadowMappingResolution=1024
```
Second, succesful run, looks like the same:
```
MipmapLevel=1
Anisotropy=1
ShadowColor=0.5
ShadowRange=0
MSAA=2
FilterMode=1
ShadowMapping=1
ShadowMappingQuality=1
ShadowMappingResolution=1024
```

**Comment by krzys-h** [comment]
After second run, open and close settings and check if the file changes

**Comment by RaptorParkowsky** [comment]
First run, with crash:
```
MipmapLevel=1
Anisotropy=1
ShadowColor=0.5
ShadowRange=0
MSAA=2
FilterMode=1
ShadowMapping=1
ShadowMappingQuality=1
ShadowMappingResolution=1024
```

Second run, go to the settings menu (all tabs, didn't change anything), and closing the game:
```
MipmapLevel=1
Anisotropy=1
ShadowColor=0.5
ShadowRange=0
MSAA=2
FilterMode=1
ShadowMapping=1
ShadowMappingQuality=0
ShadowMappingResolution=1024
```
Well, something wrong with detecting the quality shadows. Indeed my GPU doesn't support that. As far as I understand this "quality shadows" are simply the shadows with alpha channel that requires minimum 6 texture units for OGL1.4?

**Comment by krzys-h** [comment]
Yes, and that's what I excpected after that log message. Thanks, I'll try to find out what's wrong with the detection now.

**Comment by krzys-h** [comment]
Does the "Maximum texture units" log entry show the correct value?

**Comment by krzys-h** [comment]
Nevermind, fixed it already.

**Comment by RaptorParkowsky** [comment]
Yes, Everest shows me that my GPU have 4 multitexture units. The same value is in GOLD's debug logs in OpenGL 1.4. But I don't know, why I have more multitexture units (16 in debug logs) when I run GOLD in OpenGL 2.1.

**Comment by tomaszkax86** [comment]
Legacy OpenGL has *texture units* which are controlled by texture environment settings and are used for rendering without shaders. This number is generally limited to 4 or 8 and defined by GL_MAX_TEXTURE_UNITS.
Modern OpenGL has *texture image units* which are all possible binding points for textures for all shader stages. For fragment shader limit is defined by GL_MAX_TEXTURE_IMAGE_UNITS and it is usually 8 or 16, sometimes more.
Because of differences in implementation of OpenGL engines, Colobot uses GL_MAX_TEXTURE_UNITS in OpenGL 1.4, and GL_MAX_TEXTURE_IMAGE_UNITS in OpenGL 2.1 and OpenGL 3.3. Hence the difference. Shaders allow us to use more textures if we want.
