### ISSUE TITLE
Shooters destroy friendly objects in one hit

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#560]
The Astronaut, robots, building.

**Comment by krzys-h** [comment]
I just removed the thing that was supposed to prevent friendly fire because it was also working during code battles (that's why I implemented the global magnify damage setting earlier). Looks like the value that was configured as the default is just TOO BIG. It takes 24% of the shield for each shot particle. I'll fix it in a moment.

**Comment by MrSimbax** [comment]
It might be related to #356
