### ISSUE TITLE
System cursor don't change when rotating a camera

### ISSUE THREAD

**Issue by tomangelo2** [colobot/colobot#602]
In-game cursor change it texture, when we close it to border of the window. But on system cursor it still remain unchanged. Shouldn't it change too?

**Comment by RaptorParkowsky** [comment]
The same with text cursor in CBOT program editor.

**Comment by krzys-h** [comment]
This is by design - system cursor can't be changed, because it's managed internally by SDL

**Comment by RaptorParkowsky** [comment]
There's no way to use any "true" system cursors? SDL cursor only?

**Comment by tomangelo2** [comment]
If I understand correctly, in SDL2 there is a possibility to change system cursor https://wiki.libsdl.org/SDL_CreateSystemCursor

**Comment by krzys-h** [comment]
But we don't have SDL2 yet. Also, these cursors work exactly like now, except you have more predefined ones included with SDL itself I believe. Always using custom rendered cursor in SDL is their explicit design choise since SDL can also run on platforms that don't have any system cursors.
http://stackoverflow.com/questions/4058261/sdl-changing-cursor-to-windows-default

**Comment by RaptorParkowsky** [comment]
Ok, so I propose reopen that issue for future SDL refactoring. With SDL2 we should be able implement at least the cursor for text editing and more if there's any.

**Comment by krzys-h** [comment]
6d8a5bab3170aaef7aed0293d8ecb962ba2528bc
