### ISSUE TITLE
data-0.1.6 offline build fail: wget not found, music files can't be downloaded!

### ISSUE THREAD

**Issue by DAP-DarkneSS** [colobot/colobot#655]
Hello. For openSUSE packaging build must be 100% offline. Any tips please?

[   67s] + cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/usr
[   67s] -- The C compiler identification is GNU 4.8.3
[   67s] -- The CXX compiler identification is GNU 4.8.3
[   67s] -- Check for working C compiler: /var/lib/build/ccache/bin/cc
[   67s] -- Check for working C compiler: /var/lib/build/ccache/bin/cc -- works
[   67s] -- Detecting C compiler ABI info
[   68s] -- Detecting C compiler ABI info - done
[   68s] -- Detecting C compile features
[   68s] -- Detecting C compile features - done
[   68s] -- Check for working CXX compiler: /var/lib/build/ccache/bin/c++
[   68s] -- Check for working CXX compiler: /var/lib/build/ccache/bin/c++ -- works
[   68s] -- Detecting CXX compiler ABI info
[   69s] -- Detecting CXX compiler ABI info - done
[   69s] -- Detecting CXX compile features
[   69s] -- Detecting CXX compile features - done
[   70s] -- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.8", minimum required is "2.7") 
[   70s] -- Adding translation targets for help/bots
[   70s] -- Adding translation targets for help/cbot
[   72s] -- Adding translation targets for help/generic
[   72s] -- Adding translation targets for help/object
[   72s] -- Adding translation targets for level/missions
[   76s] -- Adding translation targets for level/freemissions
[   77s] -- Adding translation targets for level/exercises
[   81s] -- Adding translation targets for level/challenges
[   83s] -- Adding translation targets for level/battles
[   83s] CMake Error at music/CMakeLists.txt:67 (message):
[   83s]   wget not found, music files can't be downloaded!
[   83s] 
[   83s] 
[   83s] -- Configuring incomplete, errors occurred!

**Comment by krzys-h** [comment]
There are two ways to do that:

1. Get music files from https://colobot.info/files/music/colobot-music_ogg_0.1.6-alpha.tar.gz and extract them to directory <source_code_dir>/data/music/ (you can also get the .flac versions and convert them during build if you prefer, but the archive is much larger). They will be used from that directory instead of downloading.
2. Pass -DMUSIC=OFF to CMake and manually install files from the archive linked above into <output_data_directory>/music

I'm really hoping that the promised GitHub LFS will be available soon. I didn't realize how much harder is it to maintain the files being downloaded from HTTP, at this point I think it might have been better to have a huge git repo with binary files history.

**Comment by DAP-DarkneSS** [comment]
The first way seems to be nice.
Thank you!
