### ISSUE TITLE
Python is required to get full levels directory

### ISSUE THREAD

**Issue by DAP-DarkneSS** [colobot/colobot#669]
openSUSE was reported to not provide full levels directory content. openSUSE Build Service' (OBS) rpm doesn't really provide that files however my local one does! For some reason my local build installs python by default and the data is correctly installed. But OBS doesn't and data package becomes corrupted.

Please set cmake to generate configure error if python isn't found.

**Comment by krzys-h** [comment]
It was supposed to install files without translations if Python is not found, but I'm not sure how it workis now after @piotrdz's refactoring

**Comment by piotrdz** [comment]
Ah, it turns out there was a mistake in CMakeLists.txt in data submodule. I've fixed it on dev branch and now it works as it we intended:
 - if Python is found, level files are translated and installed along with translations
 - if Python is not found, a warning is printed, warning that translations will not be generated, and only original English files are installed.

Now, the question is, should we change that warning to actual error?
Originally, that warning was useful, as we used Perl and po4a, which is a somewhat unusual dependency for users. Now perhaps with Python we should make it mandatory.
@krzys-h: What do you think?

**Comment by krzys-h** [comment]
@piotrdz I think it would be better to make this an error, but add CMake option to disable translations (just in case somebody really doesn't want them and doesn't have Python installed)

**Comment by piotrdz** [comment]
Done.
