### ISSUE TITLE
Editor freaks out with really long file

### ISSUE THREAD

**Issue by CyborgMaster** [colobot/colobot#820]
When loading a really long file (>1000 lines), the editor freaks out.

![image](https://cloud.githubusercontent.com/assets/1882579/17652592/9e6df1e8-623d-11e6-9041-8278c2771032.png)

**Comment by CyborgMaster** [comment]
I found the code that defines the max.  I propose we increase them by 10x.

``` cpp

//! maximum number of characters in CBOT edit
const int EDITSTUDIOMAX     = 200000;
//! maximum total number of lines
const int EDITLINEMAX       = 10000;
```

**Comment by krzys-h** [comment]
I'm pretty sure this is a duplicate, but I don't have time to look for issue # right now. If you just increase the limit then at some point somebody will hit it again (and also, you are wasting RAM, very slightly but still). This whole class should be refactored to keep everything in variable-sized STL containers instead of fixed-size C arrays.
And while we're talking about it, I suggest we make this issue high priority because I saw people complaining about this limit for a long time (and I think it was even increased once already)

**Comment by CyborgMaster** [comment]
I agree, STL containers would be much better.  Should we increase the hard limits temporarily while we fix it the right way?  I think 10,000 lines is a fine limit and can't imaging anything really getting past that in a reasonable manner.  That way it would be more usable until we got around to the correct fix.

**Comment by MatiRg** [comment]
I already removed C like array in favor of STL.I need only make some adjustments and I cann make pull request.

**Comment by B-CE** [comment]
ref : #300
