### ISSUE TITLE
Update CBot inheritance documentation

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#830]
See #809 (and #807), #808, #814 and #819

**Comment by MrSimbax** [comment]
Done in https://github.com/colobot/colobot-data/commit/ea32d482c5f78e4ac92fa07cad6685a9f21645ce https://github.com/colobot/colobot-data/commit/78f5a94075d08623458254c1871726daeab0776f https://github.com/colobot/colobot-data/commit/4373e29c927b754758f77c5b2a6039dc02e62638 https://github.com/colobot/colobot-data/commit/7ac99fbd72d38c1861a366b3d8a25a3ae7b2443b

However, the current docs are lying, because `protected` and `private` don't work as they should which was mentioned several times in #540

If I didn't document smth, feel free to reopen the issue.
