### ISSUE TITLE
There is no good way to check if an alien is dead in CBOT

### ISSUE THREAD

**Issue by MrSimbax** [colobot/colobot#842]
This is especially problematic with AlienWorms.
- object pointers aren't changed automatically to `null` after the object destruction
- `object.shieldLevel` always equals `1` (except Me and bots)
- `object.lifeTime` doesn't stop after death
- `object.position.z` doesn't change when an AlienWorm is burrowed
- destroyed objects don't disappear from the `retobject()` list

**Comment by krzys-h** [comment]
> object pointers aren't changed automatically to null after the object destruction

If I remember correctly there was a comment in the code explaining that this is done on purpose because otherwise programs (especially alien programs) were crashing if the object was destroyed between checking for null value and accessing object's properties.

> object.shieldLevel always equals 1 (except Me and bots)

This is because they don't actually have a shield. `object` parameters stop updating anyway after corresponding CObject instance in the code is removed.

> object.lifeTime doesn't stop after death

Why would you assume it does? By definition it's just time since the object was created, nothing is said about destruction.

Wait... actually it shouldn't update after CObject instance is destroyed, but that happens a bit after actual death I think. Unless killing an alien doesn't destroy it's in-game object instance which would be really strange.

> object.position.z doesn't change when an AlienWorm is burrowed

That's true. I'm not sure if there is an easy way to fix this in the code other than hardcoding an AlienWorm-specific adjustement.

> destroyed objects don't disappear from the retobject() list

This could lead to race condition problems like described in the first point. Actually I thought that they DO get removed but I never actually tested it.

---

That being said, we need another way to determine if object is alive or not. I guess changing the meaning of shieldLevel for objects that don't have a sheld would be the best option (0.0 = dead, 1.0 = alive)

**Comment by krzys-h** [comment]
And here is the comment I was talking about:
```C++
void COldObject::DestroyObject(DestructionType type)
{
    // [...]
   
    if ( m_botVar != nullptr )
    {
        if ( Implements(ObjectInterfaceType::Transportable) )  // (*)
        {
            CScriptFunctions::DestroyObjectVar(m_botVar, false);
        }
    }
}

// (*)  If a robot or cosmonaut dies, the subject must continue to exist,
//  so that programs of the ants continue to operate as usual.
```
https://github.com/colobot/colobot/blob/master/src/object/old_object.cpp#L553-L554

**Comment by Arano-kai** [comment]
Current workaround:
```
int iTType = oTarget.category;
float fTDist = distance(oTarget.position, this.position);
float fTDir = direction(oTarget.position);
int iTId = oTarget.id;
fire(0.05);
while ((oTarget = radar(iTType, fTDir, 3, fTDist - 1, fTDist + 1)) != null) { //focus, d-min & d-max set for stationary target.
			if(oTarget.id != iTId) {
				message("Wrong target id, assume target is dead");
				oTarget = null;
				break;
			}
			wait(0.01);
		};

**Comment by Droog71** [comment]
I have a fix for this here: https://github.com/Droog71/colobot/commit/3b414800888a3a2a6ebafdc32ba3a8d843e7f8cf

I tested this and it's working well. 

Here is an example: 

`extern void object::Hunt()
{
	int x1 = 0;
	int y1 = 0;
	int z1 = 0;
	
	int x2 = 0;
	int y2 = 0;
	int z2 = 0;
	
	int x3 = 0;
	int y3 = 0;
	int z3 = 0;
	
	point floc = new point (0,0,0);
	
	object ant = radar(AlienAnt);
	
	while  (ant.dead == false)
	{
		x1 = (this.position.x);
		y1 = (this.position.y);
		z1 = (this.position.z);
		
		x2 = (ant.position.x);
		y2 = (ant.position.y);
		z2 = (ant.position.z);
		
		x3 = (x1+x2);
		y3 = (y1+y2);
		z3 = (z1+y2);
		
		x3 = (x3/2);
		y3 = (y3/2);
		z3 = (z3/2);
		
		floc = new point (x3,y3,z3);
		
		if (distance(this.position,ant.position) < 50)
		{
			turn(direction(ant.position));
			aim(-2,0);
			fire(0.1);
			aim(0,0);
			fire(0.1);
			aim(2,0);
			fire(0.1);
			ant = radar(AlienAnt);
		}
		else
		{
			goto(floc,ant.altitude);
		}
	}
}`

**Comment by nextghost** [comment]
Dying aliens cannot be detected by `radar()`. So my shooter bots work like this:
1. shoot 0.1s burst
2. scan the target's location with roughly 1x1m detection field
3. if the target was detected, correct aim and repeat

This works on all aliens except worms. But I think that telling apart burrowing and dying worms is an interesting puzzle that should be left in the game.

**Comment by MrSimbax** [comment]
Actually, I'm going to leave it open because this feature needs to be documented in-game.

**Comment by tomangelo2** [comment]
Feature documented in colobot/colobot-data#98
