### ISSUE TITLE
Hippomocks doesn't support arm64 or any mips*

### ISSUE THREAD

**Issue by OdyX** [colobot/colobot#853]
I have uploaded 0.1.9 to Debian unstable, and the arm64, mips and mipsel build revealed some tests failures :

```
[  FAILED  ] CApplicationUT.UpdateEventTimeCalculation_SimulationSuspended
[  FAILED  ] CApplicationUT.UpdateEventTimeCalculation_NormalOperation
[  FAILED  ] CApplicationUT.UpdateEventTimeCalculation_NegativeTimeOperation
[  FAILED  ] CApplicationUT.UpdateEventTimeCalculation_ChangingSimulationSpeed
[  FAILED  ] CApplicationUT.UpdateEventTimeCalculation_SuspendingAndResumingSimulation
[  FAILED  ] CLightManagerUT.LightSorting_UnusedOrDisabledAreSkipped
[  FAILED  ] CLightManagerUT.LightSorting_IncludeTypesAreIncluded
[  FAILED  ] CLightManagerUT.LightSorting_ExcludeTypesAreExcluded
[  FAILED  ] CLightManagerUT.LightSorting_SortingAccordingToDistance
```

You can see the full build logs 

- https://buildd.debian.org/status/fetch.php?pkg=colobot&arch=arm64&ver=0.1.9-1&stamp=1478266344
- https://buildd.debian.org/status/fetch.php?pkg=colobot&arch=mips&ver=0.1.9-1&stamp=1478270137
- https://buildd.debian.org/status/fetch.php?pkg=colobot&arch=mipsel&ver=0.1.9-1&stamp=1478269598

**Comment by krzys-h** [comment]
That is interesting, are you sure the previous versions worked correctly? I don't think we changed any related code recently.
After looking at the error in build logs, I think this could be caused by TEST_VIRTUAL not being set correctly in https://github.com/colobot/colobot/blob/master/CMakeLists.txt#L273-L277, but the compiler command line seems to be correct.

**Comment by OdyX** [comment]
0.1.9 is the first version for which (and I shouldn't have made that mistake) I have enabled tests building and running. I'm not claiming 0.1.9 has a regression, I'm claiming colobot is not (probably for a long time) working properly on arm64 or any mips*, but I can't immediately guess what is common to these architectures.

**Comment by krzys-h** [comment]
The errors themselves look more like an error of HippoMocks usage than the actual tests being wrong. The only tests that fail are the ones that use mocking, and the error messages say that a not mocked function has been called (which is pretty strange considering it works fine on other architectures and we don't have any architecture-dependent conditions).

**Comment by OdyX** [comment]
This looks like: https://github.com/dascandy/hippomocks/pull/50

**Comment by rzr** [comment]
For MIPS check this discussion too:

https://github.com/dascandy/hippomocks/pull/50

**Comment by OdyX** [comment]
Hrm. That didn't work indeed :-(

**Comment by krzys-h** [comment]
![image](https://cloud.githubusercontent.com/assets/1517255/20072603/51837d60-a529-11e6-80b9-0ef8b7cdf257.png)
Well... I think I just broke GitHub, I added that label :D Will try to reproduce and report to GitHub in a moment

**Comment by dascandy** [comment]
I'm going to go and see if I can get ARM64 working soon (as I think I have one now). Any idea where to get a MIPS target? The only one I ever used so far was a Sony dog.

**Comment by dascandy** [comment]
Something I just now noticed - you're not using the C function mocking that should be platform dependent, and known not working on MIPS. This is just virtual function mocking. Can you try to put a breakpoint in the NotImplemented function in HippoMocks and see what function call is giving this error?

**Comment by PeterBindels-TomTom** [comment]
HippoMocks is in hibernation until C++ gets proper reflection, which allows the core to be reimplemented without any use of UB. I've been spending my time in the standard committee on this and other things, instead of keeping it alive itself. Reflection currently planned for C++26 is not sufficient (does not allow creating new type with overridden virtual functions), so it would be at least c++29.

If you do want to replace it (even if temporarily), Trompe l'Oeil is a fairly modern take on the same idea.
