### ISSUE TITLE
[ERROR]: Could not create MSAA framebuffer, disabling MSAA

### ISSUE THREAD

**Issue by uhrd** [colobot/colobot#912]
colobot (Gold Edition 0.1.9-alpha) does not start when chromium (55.0.2883.87) is running.
It is only a minor annoyance, really, but I thought you should know.

[log-ok.txt](https://github.com/colobot/colobot/files/783416/log-ok.txt)
[log-chromium.txt](https://github.com/colobot/colobot/files/783417/log-chromium.txt)
[log-gdb.txt](https://github.com/colobot/colobot/files/783418/log-gdb.txt)

**Comment by krzys-h** [comment]
It's the first time I see such a weird interference from another program. @tomaszkax86 ?

**Comment by tomaszkax86** [comment]
This must have something to do with framebuffer extension on older hardware. It has supposedly a lot of annoyances that are hard to fix properly. The ```unsupported attachment format``` message tells you that the particular texture format can't be used as framebuffer attachment. If it works fine as long as Chromium is not running, it is likely something with the operating system or graphics driver. I guess Chromium or GUI management system uses OpenGL and interferes with the game somehow. There's no easy solution since older OpenGL 2.1 compatible hardware has many restrictions. It's one of the reasons most games in the past had to run in fullscreen exclusive mode for full performance. Still, this is the first time I hear about a problem like this.

Now, the game is programmed to disable features it can't use, but it shouldn't crash. Unfortunately, I'm not sure if I can fix this problem because I can't replicate the exact conditions. But I'll see what I can do.

**Comment by uhrd** [comment]
Chromium does decorate its own window, and I am running antiquated hardware. Oh, well. If someone else runs into this, maybe they can blame chromium too. 
[lshw-sanitized.txt](https://github.com/colobot/colobot/files/784353/lshw-sanitized.txt)
Is there anything else I can provide?

**Comment by uhrd** [comment]
As it turns out, blaming Chromium was a bit premature. Colobot segfaults when Teamspeak 3 is running as well. mpv and mplayer also exhibit weird behavior. I think something else entirely is going on here, and Colobot was just the first to outright crash because of it.

**Comment by tomaszkax86** [comment]
You said you have a bit dated graphics card. How much VRAM does it have? MSAA framebuffer requires quite a large amount of video RAM in order to work. For example, 4x MSAA for resolution 1024x768 requires about 24 MB of VRAM (that's 4 samples x 1024 x 768 x (4 bytes for color buffer + 4 bytes for depth buffer)). And that's just MSAA framebuffer, game requires more memory to run because of textures and vertex buffers. If there are programs that require a lot of VRAM at the same time, you may run out of it and game won't run properly. Other programs might crash for the same reason. Currently, there are no safeguards in Colobot for out-of-memory errors in graphics engine.

**Comment by uhrd** [comment]
Alright. It has 256 MB VRAM. When I start Colobot it touches 16% usage, so I don't think that's it. 
[xrandr.txt](https://github.com/colobot/colobot/files/801445/xrandr.txt)
[nvidia-settings.txt](https://github.com/colobot/colobot/files/801444/nvidia-settings.txt)

**Comment by uhrd** [comment]
I tried running a game with wine, and ran into some illegal gl instructions, so I reinstalled the legacy drivers. Now it works.
