### ISSUE TITLE
Game hangs when calling constructors in an infinite loop

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#971]
While testing some other issue I noticed that a while(true) loop that just calls a class constructor hangs the game.

```C++
public class test {}

extern void object::Nowy()
{
	while(true){
		test t = new test();
	}
}
```

**Comment by melex750** [comment]
This happens because CBotStack::AllocateStack() resets the execution countdown timer,
which is a static member of CBotStack, m_timer.
This is what causes **#874** too.

For the code in the OP, AllocateStack() is called once per loop,
when a **[stack is allocated](https://github.com/colobot/colobot/blob/dev/src/CBot/CBotVar/CBotVarClass.cpp#L391)** for executing a destructor.

With so few instructions executed inside the loop, the timer is never <= 0,
and the CBotProgram never suspends execution.

One fix could be to restore the timer value after a destructor executes.

Another fix may be:

The patch proposed in **[#874 comment](https://github.com/colobot/colobot/issues/874#issuecomment-269221581)** allows the CBotProgram to suspend execution.

With that patch, in reference to **#877**:
Destructors which execute a large number of instructions
cause the timer to be in debt with a negative value.
That debt could be paid back when CBotProgram resumes execution,
which would discourage exploiting the speed of a destructor.
